### ISSUE TITLE
Need to separate src and build files

### ISSUE THREAD

**Issue by ghost** [SidKH/markup-starter#12]
All source files must be in src directory and separate of build, not in one like now. Example from homelance http://prntscr.com/aaoovg

**Comment by SidKH** [comment]
Questionable, will think about it.

**Comment by FrontEndMonster** [comment]
need folder build in root directory same as in production folder, because we have a problem with url to images

**Comment by SidKH** [comment]
https://github.com/SidKH/markup-starter/commit/6839b6ef38bc644990b2efbc0da0b62661f5769b
