### ISSUE TITLE
Need new folder structure

### ISSUE THREAD

**Issue by ghost** [SidKH/markup-starter#33]
For WP devs needed next structure:
Build folder must contain css (with css files) and js (with js files) also they needed to compile JQuery library separate from vendors because wp contains JQuery also.

For YII devs we must create new build with:
- Build folder must be not under gitignore
- All js not compile and are not minizining. All scripts must be in separate files so we not neede vendors.js
- Production task not needed because fixies needen on 2-3 times a day.

**Comment by SidKH** [comment]
https://github.com/SidKH/markup-starter/commit/71a1223e4fc8131bd1ab723443ce2b3b9dbe412b

**Comment by SidKH** [comment]
I'll leave gitignore unchanged for non backend type of projects (to prevent bower folder to be in the git) and for the WP and YII projects develpers need to simply remove bower/ from gitignore by themselves.
