### ISSUE TITLE
Need to replace all routes to separate file

### ISSUE THREAD

**Issue by ghost** [SidKH/markup-starter#34]
Routes to all folders needs to be a variables and they should be in separate file.

**Comment by ghost** [comment]
module.exports = {
    sassDir:          'scss/',
    sassMainFileName: 'main',
    cssDir:           'css/',
    cssMainFileDir:   'css/',
    cssMainFileName:  'main',
    jsDir:            'js/',
    imgDir:           'images/',
    imgSourceDir:     'sourceimages/',
  };

**Comment by SidKH** [comment]
https://github.com/SidKH/markup-starter/commit/1c46c61ad6fd1ab721738d8df5d43895e361742e
